"""add_departments_and_feature_permissions

Revision ID: 84a829cdf24b
Revises: 450ae450e023
Create Date: 2026-02-06 09:13:52.148847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84a829cdf24b'
down_revision: Union[str, None] = '450ae450e023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('featurepermissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_featurepermissions_feature'), 'featurepermissions', ['feature'], unique=False)
    op.create_index(op.f('ix_featurepermissions_id'), 'featurepermissions', ['id'], unique=False)
    op.create_index(op.f('ix_featurepermissions_tenant_id'), 'featurepermissions', ['tenant_id'], unique=False)
    op.add_column('documents', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_department_id'), 'documents', ['department_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_department_id'), table_name='documents')
    op.drop_column('documents', 'department_id')
    op.drop_index(op.f('ix_featurepermissions_tenant_id'), table_name='featurepermissions')
    op.drop_index(op.f('ix_featurepermissions_id'), table_name='featurepermissions')
    op.drop_index(op.f('ix_featurepermissions_feature'), table_name='featurepermissions')
    op.drop_table('featurepermissions')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
